/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Dashboard;

import Background.FormBackgroundPanel;
import com.formdev.flatlaf.FlatClientProperties;
//import com.formdev.flatlaf.FlatClientProperties;
import java.awt.event.*;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Diaz Nuraji
 */
public class FormDashboardFrame extends javax.swing.JFrame {

    /**
     * Creates new form FormDashboardFrame
     */
    public FormDashboardFrame() {
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        initComponents();
        execute();
//        pnTopBar.putClientProperty(FlatClientProperties.STYLE, ""
//                + "background:rgb(192,167,150)");
//        pnUtama2.putClientProperty(FlatClientProperties.STYLE, ""
//                + "arc:12;" // Sudut
//                + "background:rgb(60,60,60)");
//        pnUtama1.putClientProperty(FlatClientProperties.STYLE, ""
//                + "arc:12;" // Sudut
//                + "background:rgb(60,60,60)");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnSideBar = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pnMenu = new javax.swing.JPanel();
        lbBack = new javax.swing.JLabel();
        pnTopBar = new javax.swing.JPanel();
        pnUtama1 = new javax.swing.JPanel();
        pnUtama2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        pnSideBar.setBackground(new java.awt.Color(104, 132, 179));
        pnSideBar.setPreferredSize(new java.awt.Dimension(250, 380));

        jScrollPane1.setBorder(null);

        pnMenu.setBackground(new java.awt.Color(104, 132, 179));
        pnMenu.setLayout(new javax.swing.BoxLayout(pnMenu, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane1.setViewportView(pnMenu);

        lbBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/LogoutLight48.png"))); // NOI18N
        lbBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbBackMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnSideBarLayout = new javax.swing.GroupLayout(pnSideBar);
        pnSideBar.setLayout(pnSideBarLayout);
        pnSideBarLayout.setHorizontalGroup(
            pnSideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnSideBarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnSideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(pnSideBarLayout.createSequentialGroup()
                        .addComponent(lbBack, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 190, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnSideBarLayout.setVerticalGroup(
            pnSideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnSideBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbBack)
                .addContainerGap())
        );

        getContentPane().add(pnSideBar, java.awt.BorderLayout.LINE_START);

        pnTopBar.setBackground(new java.awt.Color(104, 132, 179));

        javax.swing.GroupLayout pnTopBarLayout = new javax.swing.GroupLayout(pnTopBar);
        pnTopBar.setLayout(pnTopBarLayout);
        pnTopBarLayout.setHorizontalGroup(
            pnTopBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 837, Short.MAX_VALUE)
        );
        pnTopBarLayout.setVerticalGroup(
            pnTopBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        getContentPane().add(pnTopBar, java.awt.BorderLayout.PAGE_START);

        pnUtama2.setBackground(new java.awt.Color(224, 235, 245));
        pnUtama2.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout pnUtama1Layout = new javax.swing.GroupLayout(pnUtama1);
        pnUtama1.setLayout(pnUtama1Layout);
        pnUtama1Layout.setHorizontalGroup(
            pnUtama1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnUtama2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnUtama1Layout.setVerticalGroup(
            pnUtama1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnUtama2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(pnUtama1, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(853, 458));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        pnUtama2.add(new FormBackgroundPanel());
        pnUtama2.repaint();
        pnUtama2.revalidate();
    }//GEN-LAST:event_formWindowOpened

    private void lbBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbBackMouseClicked
        new Login.FormLoginFrame().setVisible(true);
        dispose();
    }//GEN-LAST:event_lbBackMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormDashboardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormDashboardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormDashboardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormDashboardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormDashboardFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbBack;
    public static javax.swing.JPanel pnMenu;
    private javax.swing.JPanel pnSideBar;
    private javax.swing.JPanel pnTopBar;
    private javax.swing.JPanel pnUtama1;
    private javax.swing.JPanel pnUtama2;
    // End of variables declaration//GEN-END:variables
   
      
    private void execute() {
        ImageIcon iconTransaksi = new ImageIcon(getClass().getResource("/Icon/TransaksiLight48.png"));
        ImageIcon iconEvent = new ImageIcon(getClass().getResource("/Icon/EventLight48.png"));
        ImageIcon iconGudang = new ImageIcon(getClass().getResource("/Icon/GudangLight48.png"));
        ImageIcon iconPegawai = new ImageIcon(getClass().getResource("/Icon/PegawaiLight48.png"));
        ImageIcon subiconList = new ImageIcon(getClass().getResource("/Icon/ListLight48.png"));
        ImageIcon subiconKasir = new ImageIcon(getClass().getResource("/Icon/KasirLight48.png"));
        ImageIcon subiconBarang = new ImageIcon(getClass().getResource("/Icon/BarangLight48.png"));
        ImageIcon subiconStok = new ImageIcon(getClass().getResource("/Icon/StokLight48.png"));
        
        FormMenuItem subMenuKasir = new FormMenuItem(null, subiconKasir, true, "Kasir", (ActionEvent e) -> {
            pnUtama2.removeAll();
            pnUtama2.add(new Transaksi.FormKasirPanel());
            pnUtama2.repaint();
            pnUtama2.revalidate();
        });
        FormMenuItem subMenuList = new FormMenuItem(null, subiconList, true, "List", (ActionEvent e) -> {
            pnUtama2.removeAll();
            pnUtama2.add(new Transaksi.FormListPanel());
            pnUtama2.repaint();
            pnUtama2.revalidate();
        });
        FormMenuItem menuKasir = new FormMenuItem(iconTransaksi, null, false, "Transaksi", null, subMenuKasir, subMenuList);
        FormMenuItem menuEvent = new FormMenuItem(iconEvent, null, false, "Event", (ActionEvent e) -> {
            pnUtama2.removeAll();
            pnUtama2.add(new Event.FormEventPanel());
            pnUtama2.repaint();
            pnUtama2.revalidate();
        });
        FormMenuItem subMenuBarang = new FormMenuItem(null, subiconBarang, true, "Barang", (ActionEvent e) -> {
            pnUtama2.removeAll();
            pnUtama2.add(new Barang.FormBarangPanel());
            pnUtama2.repaint();
            pnUtama2.revalidate();
        });
        FormMenuItem subMenuStok = new FormMenuItem(null, subiconStok, true, "Stok", (ActionEvent e) -> {
            pnUtama2.removeAll();
            pnUtama2.add(new Barang.FormStokPanel());
            pnUtama2.repaint();
            pnUtama2.revalidate();
        });
        FormMenuItem menuBarang = new FormMenuItem(iconGudang, null, false, "Gudang", null, subMenuBarang, subMenuStok);
        FormMenuItem menuPegawai = new FormMenuItem(iconPegawai, null, false, "Akun", (ActionEvent e) -> {
            pnUtama2.removeAll();
            pnUtama2.add(new Pegawai.FormPegawaiPanel());
            pnUtama2.repaint();
            pnUtama2.revalidate();
        });
        addMenu(menuKasir, menuBarang, menuPegawai, menuEvent);
    }
 
    private void addMenu(FormMenuItem... menu) {
        for (FormMenuItem menus : menu) {
            pnMenu.add(menus);
            ArrayList<FormMenuItem> subMenu = menus.getSubMenu();
            for (FormMenuItem m : subMenu) {
                addMenu(m);
            }
        }
        pnMenu.revalidate();
        
    }
   
 
}                                              


