/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package login;

import com.formdev.flatlaf.*;
import java.awt.Dimension;
import javax.swing.*;
import static main.Main.*;

/**
 *
 * @author Diaz Nuraji
 */
public class FormLoginFrame extends javax.swing.JFrame {

    private static FormLoginPanel formPanel;
    private static FormLoginFrame formFrame;

    /**
     * Creates new form main
     */
    public FormLoginFrame() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        formPanel = new FormLoginPanel();
        setContentPane(formPanel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new Dimension(SetSize(0.6)[0], SetSize(0.9)[1]));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 298, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void Form() {
        ThemeListener = isDark -> {
            SwingUtilities.invokeLater(() -> {
                if (!isDark) {
                    FlatLightLaf.setup();
                } else {
                    FlatDarkLaf.setup();
                }
                if (formFrame != null) {
                    SwingUtilities.updateComponentTreeUI(formFrame);
                } else {
                    formFrame = new FormLoginFrame();
                    formFrame.setVisible(true);
                }
            });
        };
        ThemeListener.accept(Detector.isDark());
        Detector.registerListener(ThemeListener);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
