/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Transaksi;

import com.formdev.flatlaf.FlatClientProperties;
import java.sql.*;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Koneksi.Koneksi;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Calendar;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Diaz Nuraji
 */
public class FormKasirPanel extends javax.swing.JPanel {

    private static Connection cn;
    private static ResultSet rs;
    private static Statement st;
    private static PreparedStatement pst;
    public static String[] barang = new String[10];

    /**
     * Creates new form FormEventPanel
     */
    public FormKasirPanel() {
        initComponents();
        txtIDPegawai.setText(FormLogin.FormLoginFrame.namaPegawai);
        txtTransaksi.setText(GenerateID());
    }

    public String GenerateID() {
        Random random = new Random();
        // Random number 10000000 to 99999999
        int number = random.nextInt(89999999) + 10000000;
        String id = "TRX_" + number;
        return id;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnKasir = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnPilih = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtIDPegawai = new javax.swing.JTextField();
        btnFinal = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtTransaksi = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtKeterangan = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        btnHitung = new javax.swing.JButton();
        lbTotal = new javax.swing.JLabel();

        pnKasir.setPreferredSize(new java.awt.Dimension(800, 600));

        jLabel5.setText("Kasir");

        btnPilih.setText("Pilih Barang");
        btnPilih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPilihActionPerformed(evt);
            }
        });

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("ID Pegawai");

        txtIDPegawai.setEnabled(false);

        btnFinal.setText("Proses");
        btnFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalActionPerformed(evt);
            }
        });

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("ID Transaksi");

        txtTransaksi.setEnabled(false);

        jLabel2.setText("Keterangan:");

        txtKeterangan.setColumns(20);
        txtKeterangan.setRows(5);
        jScrollPane1.setViewportView(txtKeterangan);

        jLabel3.setText("Total Bayar:");

        btnHitung.setText("Hitung");
        btnHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnKasirLayout = new javax.swing.GroupLayout(pnKasir);
        pnKasir.setLayout(pnKasirLayout);
        pnKasirLayout.setHorizontalGroup(
            pnKasirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnKasirLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnKasirLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnKasirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnKasirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtTransaksi, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                        .addGroup(pnKasirLayout.createSequentialGroup()
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel1))
                        .addComponent(btnPilih, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtIDPegawai))
                    .addComponent(btnHitung))
                .addGap(69, 69, 69)
                .addGroup(pnKasirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnFinal)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                    .addComponent(jLabel3)
                    .addComponent(lbTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        pnKasirLayout.setVerticalGroup(
            pnKasirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnKasirLayout.createSequentialGroup()
                .addComponent(jLabel5)
                .addGap(14, 14, 14)
                .addGroup(pnKasirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnKasirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnKasirLayout.createSequentialGroup()
                        .addComponent(txtTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(pnKasirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnKasirLayout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(jLabel1))
                            .addGroup(pnKasirLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6)))
                        .addGap(7, 7, 7)
                        .addComponent(txtIDPegawai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnKasirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnKasirLayout.createSequentialGroup()
                        .addComponent(lbTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addGroup(pnKasirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnFinal)
                            .addComponent(btnHitung)))
                    .addComponent(btnPilih))
                .addGap(324, 324, 324))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnKasir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnKasir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnPilihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPilihActionPerformed
        new FormPilihBarangFrame().setVisible(true);
    }//GEN-LAST:event_btnPilihActionPerformed

    private void btnFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalActionPerformed
        // Tanggal
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
        String datetime = LocalDateTime.now().format(formatter);

        try {
            cn = Koneksi.koneksiDB();
            String query = "INSERT INTO transaksi (id_transaksi, id_pegawai, keterangan, tanggal";

            // for id_barang_0 to id_barang_9
            for (int i = 0; i < 10; i++) {
                query += ", id_barang_" + i;
            }

            // id_transaksi, id_pegawai, keterangan, tanggal
            query += ") VALUES (?, ?, ?, ?";

            // for id_barang_0 to id_barang_9
            for (int i = 0; i < 10; i++) {
                query += ", ?";
            }

            query += ")";

            pst = cn.prepareStatement(query);
            pst.setString(1, txtTransaksi.getText()); // id_transaksi
            pst.setString(2, txtIDPegawai.getText()); // id_pegawai
            pst.setString(3, txtKeterangan.getText()); // keterangan
            pst.setString(4, datetime); // tanggal

            // Add id_barang values from barang array
            for (int i = 0; i < 10; i++) {
                if (barang[i] != null) {
                    pst.setString(5 + i, barang[i]);
                } else {
                    pst.setNull(5 + i, Types.VARCHAR);
                }
            }

            pst.executeUpdate();

            JOptionPane.showMessageDialog(this, "Transaksi berhasil !!!");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Transaksi gagal, " + e.getMessage());
        }
    }//GEN-LAST:event_btnFinalActionPerformed

    private void btnHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungActionPerformed
        int totalPrice = 0; // Total harga
        HashMap<String, Integer> itemCount = new HashMap<>(); // Map untuk menyimpan jumlah barang
        HashMap<String, String> namaMap = new HashMap<>(); // Map untuk menyimpan pemetaan id_barang -> nama

        // Hitung kemunculan setiap item dalam array barang dan ambil nama dari database
        for (String item : barang) {
            if (item != null) {
                // Periksa apakah item sudah ada dalam map itemCount
                if (itemCount.containsKey(item)) {
                    // Jika ya, tambahkan jumlahnya
                    itemCount.put(item, itemCount.get(item) + 1);
                } else {
                    // Jika tidak, inisialisasi jumlah dengan 1
                    itemCount.put(item, 1);
                    try {
                        // Ambil koneksi ke database
                        cn = Koneksi.koneksiDB();
                        String query = "SELECT * FROM barang WHERE id_barang = ?";
                        pst = cn.prepareStatement(query);
                        pst.setString(1, item);
                        rs = pst.executeQuery();
                        if (rs.next()) {
                            // Ambil nama dari hasil pencarian
                            String nama = rs.getString("nama");
                            // Simpan pemetaan id_barang -> nama dalam namaMap
                            namaMap.put(item, nama);
                        }
                    } catch (SQLException e) {
                        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
                    }
                }
            }
        }

        // Buat StringBuilder untuk menyusun hasil akhir
        StringBuilder result = new StringBuilder();

        // Iterasi melalui array barang untuk menyisipkan item dengan jumlah
        Set<String> uniqueItems = new HashSet<>();
        for (String item : barang) {
            if (item != null && !uniqueItems.contains(item)) { // Jika item belum ditambahkan sebelumnya
                uniqueItems.add(item); // Tandai item sebagai sudah ditambahkan
                // Ambil nama dari namaMap menggunakan id_barang
                String nama = namaMap.get(item);
                // Periksa apakah jumlahnya lebih dari 1, tambahkan "x[jumlah]"
                if (itemCount.get(item) > 1) {
                    result.append(nama).append(" x").append(itemCount.get(item));
                } else {
                    result.append(nama);
                }
                result.append("\n"); // Tambahkan baris baru
            }
        }
        txtKeterangan.setText(result.toString());

        // Calculate the total price
        for (String barangs : barang) {
            if (barangs != null) {
                try {
                    cn = Koneksi.koneksiDB();
                    String query = "SELECT * FROM barang WHERE id_barang = ?";
                    pst = cn.prepareStatement(query);
                    pst.setString(1, barangs);
                    rs = pst.executeQuery();
                    if (rs.next()) {
                        int harga = rs.getInt("harga");
                        totalPrice += harga;
                    }
                } catch (SQLException e) {
                    JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
                }
            }
        }

        lbTotal.setText(String.valueOf(totalPrice));
    }//GEN-LAST:event_btnHitungActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFinal;
    private javax.swing.JButton btnHitung;
    private javax.swing.JButton btnPilih;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbTotal;
    private javax.swing.JPanel pnKasir;
    private javax.swing.JTextField txtIDPegawai;
    private javax.swing.JTextArea txtKeterangan;
    private javax.swing.JTextField txtTransaksi;
    // End of variables declaration//GEN-END:variables
}
