/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Transaksi;

import com.formdev.flatlaf.FlatClientProperties;
import java.sql.*;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Koneksi.Koneksi;
import java.awt.Color;

/**
 *
 * @author Diaz Nuraji
 */
public class FormListPanel extends javax.swing.JPanel {

    private static Connection cn;
    private static ResultSet rs;
    private static Statement st;
    private static PreparedStatement pst;

    /**
     * Creates new form FormEventPanel
     */
    public FormListPanel() {
        initComponents();
        UpdateTable();
        transparan();
        pnTransaksi.putClientProperty(FlatClientProperties.STYLE, ""
                + "arc:12;" // Sudut
                + "background:$Login.background");
        lbTitleTransaksi.putClientProperty(FlatClientProperties.STYLE, ""
                + "font:+bold +20");
        if (Login.FormLoginFrame.isAdmin.isSelected()) {
    btnHapus.setEnabled(true);
} else {
    btnHapus.setEnabled(false);
    // Set warna
    Color bgColor = new Color(104, 132, 179);

    btnHapus.setBackground(bgColor);

    btnHapus.setOpaque(true);

    btnHapus.setBorderPainted(false);

    btnHapus.setContentAreaFilled(false);

    btnHapus.repaint();
}

    }
    
    public void transparan(){
        btnHapus.setBackground(new Color(0,0,0,0));
    }


    public void UpdateTable() {
        DefaultTableModel tbl = new DefaultTableModel();
        tbl.addColumn("ID Detail Transaksi");
        tbl.addColumn("ID Pegawai");
        tbl.addColumn("Tanggal");
        tbl.addColumn("Total");
        Table.setModel(tbl);
        try {
            cn = Koneksi.koneksiDB();
            st = cn.createStatement();
            rs = st.executeQuery("SELECT * FROM detail_transaksi ORDER by tanggal DESC");

            while (rs.next()) {
                tbl.addRow(new Object[]{
                    rs.getString("id_detail_transaksi"),
                    rs.getString("id_pegawai"),
                    rs.getString("tanggal"),
                    rs.getString("total"),});
                Table.setModel(tbl);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Gagal memuat data: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnTransaksi = new javax.swing.JPanel();
        lbTitleTransaksi = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        btnHapus = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtKeterangan = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(215, 223, 235));

        pnTransaksi.setPreferredSize(new java.awt.Dimension(960, 600));
        pnTransaksi.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbTitleTransaksi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pnTransaksi.add(lbTitleTransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 750, 60));

        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Table);

        pnTransaksi.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 860, 250));

        btnHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONTA/btnHAPUS.png"))); // NOI18N
        btnHapus.setBorder(null);
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        pnTransaksi.add(btnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 530, 110, 40));

        txtKeterangan.setColumns(20);
        txtKeterangan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtKeterangan.setRows(5);
        txtKeterangan.setBorder(null);
        jScrollPane2.setViewportView(txtKeterangan);

        pnTransaksi.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 860, 140));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONTA/TRANSAKSI.png"))); // NOI18N
        pnTransaksi.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        int row = Table.getSelectedRow();

        if (row < 0) {
            // Error if row not selected
            JOptionPane.showMessageDialog(null, "Pilih data yang akan dihapus");
            return;
        }
        // get value from first row
        String id_detail_transaksi = Table.getValueAt(row, 0).toString();
        String id_transaksi = null;

        try {
            cn = Koneksi.koneksiDB();

            // Get id_transaksi
            pst = cn.prepareStatement("SELECT id_transaksi FROM detail_transaksi WHERE id_detail_transaksi = ?");
            pst.setString(1, id_detail_transaksi);
            rs = pst.executeQuery();
            if (rs.next()) {
                id_transaksi = rs.getString("id_transaksi");
            }

            // Delete from detail_transaksi table
            pst = cn.prepareStatement("DELETE FROM detail_transaksi WHERE id_detail_transaksi = ?");
            pst.setString(1, id_detail_transaksi);
            pst.executeUpdate();

            // Delete from transaksi table
            pst = cn.prepareStatement("DELETE FROM transaksi WHERE id_transaksi = ?");
            pst.setString(1, id_transaksi);
            pst.executeUpdate();

            JOptionPane.showMessageDialog(null, "Data Berhasil Di Hapus");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Gagal menghapus data: " + e.getMessage());
        }
        UpdateTable();
        txtKeterangan.setText("");
    }//GEN-LAST:event_btnHapusActionPerformed

    private void TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableMouseClicked
        int row = Table.getSelectedRow();
        String id_detail_transaksi = Table.getValueAt(row, 0).toString();
        String keterangan = null;
        String query = "SELECT t.keterangan "
        + "FROM transaksi t "
        + "JOIN detail_transaksi dt ON t.id_transaksi = dt.id_transaksi "
        + "WHERE dt.id_detail_transaksi = ?";
        try {
            cn = Koneksi.koneksiDB();
            pst = cn.prepareStatement(query);
            pst.setString(1, id_detail_transaksi);
            rs = pst.executeQuery();
            if (rs.next()) {
                keterangan = rs.getString("keterangan");
            } // Move cursor to first row
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Gagal memuat data: " + e.getMessage());
        }
        txtKeterangan.setText(keterangan);
    }//GEN-LAST:event_TableMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Table;
    private javax.swing.JButton btnHapus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbTitleTransaksi;
    private javax.swing.JPanel pnTransaksi;
    private javax.swing.JTextArea txtKeterangan;
    // End of variables declaration//GEN-END:variables
}
